### ISSUE TITLE
Monkeypatched Task.apply_async getting TaskType instead of Task argument

### ISSUE THREAD

**Issue by bennylope** [resulto-admin/django-celery-fulldbresult#17]
Here's a problem I've noticed only with the latest version of django-celery-fulldbresult.

**Description of problem**

After setting up the fulldbresult backend with an existing Celery and django-celery installation, I saw this error from the Celery beat worker:

``` python
SchedulingError: Couldn't apply scheduled task Send queued mail: unbound method apply_async() must be called with Task instance as first argument (got TaskType instance instead)
```

The particular task had been run previously as set up as a djcelery PeriodicTask in the admin.

**Environment**

The worker is executed with the `./manage.py celery beat` command.

Package versions:

`django`: 1.9.7
`celery`: 3.1.23
`django-celery`: 3.1.17
`django-celery-fulldbresult`: 0.5.0

_Everything works fine if I drop down to the previous version of `django-celery-fulldbersult`, 0.4.1.

**My analysis**

I added `IPython.embed` into the `new_apply_async` function used to monkeypatch `Task.apply_async` (as the [first line in the function](https://github.com/resulto-admin/django-celery-fulldbresult/blob/799ee8bbbe73c8969feab40e7c5b34cf8e1cbf72/django_celery_fulldbresult/__init__.py#L16)) and discovered that `self` is a `celery.app.TaskType` instance, not a `celery.app.Task` instance. 

Here's the session output (with a few names updated):

``` console
In [1]: type(self)
Out[1]: [2016-08-29 17:21:20,401: WARNING/MainProcess] celery.app.task.TaskType
In [2]: self??
[2016-08-29 17:21:22,875: WARNING/MainProcess] Init signature: self(name, *args, **kwargs)
Source:
@task(name="run_management_command")
def run_management_command(name, *args, **kwargs):
    call_command(name, *args, **kwargs)
File:           ~/Projects/myproject/app/tasks.py
Type:           TaskType
```

That's the full task definition but Python sees a `TaskType` not a `Task` instance. I can't quite put my finger on why this is happening, but I do wonder if it has to do with how the monkeypatch is applied. Of course if no one else is experiencing this then not sure how that'd be the case.

**Comment by bartdag** [comment]
Hi, thanks for your report and sorry for the delay (I was on vacation :-) ).

First, I just realized that the monkey patch should only be done if DJANGO_CELERY_FULLDBRESULT_SCHEDULE_ETA is True so we'll fix that.

Second, I'll investigate what I can find about TaskType, maybe there is an issue with inheritance. I'll report here what I find!

**Comment by bennylope** [comment]
> Second, I'll investigate what I can find about TaskType, maybe there is an issue with inheritance. I'll report here what I find!

Likely the culprit (as best as I can tell).

> sorry for the delay (I was on vacation :-) ).

No worries, thanks for looking into this! 👍 In my use case the previous version is working just fine.

**Comment by bartdag** [comment]
So TaskType is a metaclass. 

I see you are using `@task(name="run_management_command")` instead of @app.task or @shared_task. Do you experience the same problem if you use @shared_task (not sure if it's possible in your current codebase)?

Looking at Celery code, we might have more success by providing an abstract Task class too.

**Comment by bennylope** [comment]
The app still uses old style Celery setup (wholly dependent on django-celery) but I'll see how using, say, `shared_task` works.

**Comment by bennylope** [comment]
Welp, using `@shared_task` works. _If_ there's a fix needed here it's probably just a documentation note to developers not to use `@task` directly. Solved for me, I'll let you decided if it's necessary to keep open or not. Thanks for the response!

**Comment by bartdag** [comment]
Great to know it worked. Thanks a lot for trying! I'll keep the ticket open because there is some work to do to be less agressive with the monkey patching and offer an alternative, i.e., an abstract task class.
